### ISSUE TITLE
Add kivy/pyjnius team member(s) as maintainer

### ISSUE THREAD

**Issue by hanslovsky** [conda-forge/pyjnius-feedstock#9]
@hadim I think that it would be useful to have representation from kivy/pyjnius team on the maintainer list. Thanks to your great work it seems that this recipe is pretty stable now and maintenance effort would be small for additional maintainers. If you agree I will start an appropriate issue on the pyjnius repo, asking for (a member of) the team to represent kivy/pyjnius on the maintainer list.

**Comment by hadim** [comment]
Sure go ahead. It's a good idea.
